- name: Create .config/offlineimap directory
  file:
    path: /home/{{ username }}/.config/offlineimap/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Auth script
  copy:
    src: HOME/.config/offlineimap/auth.py
    dest: /home/{{ username }}/.config/offlineimap/auth.py
    mode: '0700'
  become: yes
  become_user: "{{ username }}"

- name: Configure offlineimap
  template:
    src: HOME/.config/offlineimap/config.j2
    dest: /home/{{ username }}/.config/offlineimap/config
    mode: '0600'
  become: yes
  become_user: "{{ username }}"

- name: Configure offlineimap postsync
  template:
    src: HOME/.config/offlineimap/postsync.sh.j2
    dest: /home/{{ username }}/.config/offlineimap/postsync.sh
    mode: '0700'
  become: yes
  become_user: "{{ username }}"

- name: Ensure systemd default target dir exists for user
  file:
    path: /home/{{ username }}/.config/systemd/user/default.target.wants/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Enable offlineimap service
  file:
    src: /usr/lib/systemd/user/offlineimap@.service
    dest: /home/{{ username }}/.config/systemd/user/default.target.wants/offlineimap@{{ item.account_name }}.service
    state: link
  become: yes
  become_user: "{{ username }}"
  loop: "{{ email_accounts }}"

- name: Restart offlineimap service
  systemd:
    name: offlineimap@{{ item.account_name }}
    scope: user
    state: restarted
    daemon_reload: yes
  become: yes
  become_user: "{{ username }}"
  failed_when: False
  loop: "{{ email_accounts }}"
