- name: Create davmail config dir
  file:
    dest: /home/{{ username }}/.config/davmail/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Configure davmail
  copy:
    src: HOME/.config/davmail/davmail.properties
    dest: /home/{{ username }}/.config/davmail/davmail.properties
    mode: '0600'
  become: yes
  become_user: "{{ username }}"

- name: Install davmail service
  copy:
    src: HOME/.config/systemd/user/davmail.service
    dest: /home/{{ username }}/.config/systemd/user/davmail.service
    mode: '0600'
  become: yes
  become_user: "{{ username }}"

- name: Ensure systemd default target dir exists for user
  file:
    path: /home/{{ username }}/.config/systemd/user/default.target.wants/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Enable davmail service
  file:
    src: /home/{{ username }}/.config/systemd/user/davmail.service
    dest: /home/{{ username }}/.config/systemd/user/default.target.wants/davmail.service
    state: link
  become: yes
  become_user: "{{ username }}"

- name: Restart davmail service
  systemd:
    name: davmail
    scope: user
    state: restarted
    daemon_reload: yes
  become: yes
  become_user: "{{ username }}"
  failed_when: False
