---
- block:
  - import_tasks: prepare.yml
    tags:
      - prepare
      - syncthing.prepare
  - import_tasks: install.yml
    tags:
      - install
      - syncthing.install
  - import_tasks: configure.yml
    tags:
      - configure
      - syncthing.configure
  tags:
    - syncthing

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - syncthing.uninstall
